version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "syslog:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-producer:
    build: ./kafka_producer
    container_name: kafka_producer
    restart: always

  spark:
    build: ./spark_analytics
    container_name: spark_analytics
    restart: always
    ports:
      - "4040:4040"
    environment:
      PYSPARK_SUBMIT_ARGS: --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5 /app/main.py
    volumes:
      - ~/spark_analytics:/spark_analytics

